### PR TITLE
Improve and extend DateTime/DateTimeOffset generation

### PR DESCRIPTION
**Pull request by cmeeren**
This PR consists of these changes, each in a separate commit:
* Improve correctness of Gen.dateTime docs (`DateTime` is decidedly not an instant in time; `DateTimeOffset` is). This change was also done for consistency with the new functions added in later commits.
* Added `Gen.dateTimeOffset`. It's a "primitive" that is non-trivial to generate (care must be taken to avoid overflows due to adding offsets around the min/max values) and should be in fsharp-hedgehog
* Added ranged variants of `Gen.dateTime` and `Gen.dateTimeOffset`, allowing users to specify their own date ranges (I have myself come across the need to limit the date ranges due to complicated time zone stuff some country did a hundred years ago, which is not interesting to account for in my domain)
* Implemented `dateTime` and `dateTimeOffset` in terms of their ranged variants

There is one other change I'd like to make, but for some reason it won't compile: I'd like to change the default range of `dateTime` and `dateTimeOffset` from `constant` to either `linear` or `exponential`. I don't see a reason why it should be size-independent. But when I tried to change it, I get compile errors:

image

### CODE REVIEW

**Comment by cmeeren** [comment]
We should probably add tests, at least for the `DateTimeOffset` generator(s). I experimented a bit with them now, and there may be a bug. I'll have a look at it tomorrow.

**Comment by cmeeren** [comment]
The bug is now fixed. I have experimented with both `dateTimeOffset` and `dateTimeOffsetRanged` in FSI. They seem to produce sensible values according to the size (apart from the default range being `constant`, as previously mentioned), and never crash.

**Comment by cmeeren** [comment]
To be clear, the only outstanding thing here is the compilation error I mentioned, and that can be done later (e.g. in another PR) or not at all (if you don't agree with the change). So feel free to review.

**Comment by moodmosaic** [comment]
Interesting. Is that issue happening on master or just in v0.8.3?

**Comment by cmeeren** [comment]
The compilation error? On master (and 0.8.4). I discovered it while working on this PR, so I don't see how 0.8.3 is relevant.

**Comment by moodmosaic** [comment]
>There is one other change I'd like to make, but for some reason it won't compile: I'd like to change the default range of `dateTime` and `dateTimeOffset` from `constant` to either `linear` or `exponential`. I don't see a reason why it should be size-independent. But when I tried to change it, I get compile errors

Perhaps we're missing something in Numeric.fs(?) :thinking: Reminds me of https://github.com/hedgehogqa/fsharp-hedgehog/issues/156.

File: src/Hedgehog/Gen.fs [hunk 1]
```diff
@@ -515,21 +515,43 @@ module Gen =
...
+                (14L * 60L)
+                ((ticks - DateTimeOffset.MinValue.Ticks) / TimeSpan.TicksPerMinute)
+            let! offsetMinutes = int (Range.linearFrom 0 (Operators.int minOffsetMinutes) (Operators.int maxOffsetMinutes))
+            return System.DateTimeOffset(ticks, TimeSpan.FromMinutes (Operators.float offsetMinutes))
+        }
+
+    /// Generates a random DateTime.
+    [<CompiledName("DateTime")>]
+    let dateTime : Gen<System.DateTime> =
+        dateTimeRanged (Range.constantFrom (DateTime (2000, 1, 1)) DateTime.MinValue DateTime.MaxValue)
```
Comment (moodmosaic) [inline src/Hedgehog/Gen.fs:547]: Perhaps we should just deprecate those in favor or the ranged ones with v0.9.0? (That is, we keep the same name `dateTime`, `dateTimeOffset` but we accept `Range` as parameter.)

After all, it's just a one liner to define the old one (assuming we name the ranged one as `dateTime`):

```f#
dateTime (Range.constantFrom (DateTime (2000, 1, 1)) DateTime.MinValue DateTime.MaxValue)
```

I understand that it's a breaking change, but we're v0.x so we should consider that trade-off if it helps keep the API clean.

**Review by moodmosaic — COMMENTED** [review]
:+1: :100: I left a comment, but overall this looks great.

File: src/Hedgehog/Gen.fs (hunk 1 above)
Comment (cmeeren) [reply src/Hedgehog/Gen.fs:547]: Sure. Do you want me to remove the non-ranged `datetimeoffset` then, since that's a new part of the API? No sense in adding something that's deprecated from day 1. :)

Comment (cmeeren) [reply src/Hedgehog/Gen.fs:547]: Or, when you say "deprecate", do you mean that we should just remove the non-ranged ones altogether?

Comment (moodmosaic) [reply src/Hedgehog/Gen.fs:547]: Yes, I think we should take them out. Are you OK with this @TysonMN?

Comment (TysonMN) [reply src/Hedgehog/Gen.fs:547]: If I correctly understand, then yes.  Here are my thoughts based on that linked code.  I think they are consistent with the conclusion being reached here.

There are two functions there: `dateTimeOffsetRanged` and `dateTimeOffset`.  Of course the preferred name is the shorter `dateTimeOffset`.  I think the function accepting `Range<DateTimeOffset>` should have the preferred name (i.e. `dateTimeOffset`).  Then we can either remove the other function or rename it to something like `dateTimeOffsetWithMaxRange`.

Comment (moodmosaic) [reply src/Hedgehog/Gen.fs]: Yep. I think that's one of the very few (if not the first) case in the last 10+ years where I think introducing a lil breaking change is actually fine.

**Review by moodmosaic — APPROVED** [review]
:+1:

**Comment by cmeeren** [comment]
I have made the change now. Note:
* The test `dateTime shrinks to correct mid-value` still makes sense if one wants to test that it shrinks correctly based on the range. I left it in.
* When fixing the tests, I had to use `Range.constant`.  See OP for details. Also, it's not possible to use the `*Bounded` ranges, e.g. `Range.constantBounded` gives an error because `DateTime` does not support `Zero`.

**Comment by moodmosaic** [comment]
>[..]I had to use `Range.constant` for the reason described in the OP. Furthermore, it's not possible to use the `*Bounded` ranges, e.g. `Range.constantBounded` gives an error because `DateTime` does not support `get_Zero`.

I'd like to look into this before merging, if that's OK.

**Comment by cmeeren** [comment]
> I'd like to look into this before merging, if that's OK.

Absolutely.

**Comment by cmeeren** [comment]
Any chance to have a look at this so it can be merged? :)

**Comment by moodmosaic** [comment]
> > [..]I had to use `Range.constant` for the reason described in the OP. Furthermore, it's not possible to use the `*Bounded` ranges, e.g. `Range.constantBounded` gives an error because `DateTime` does not support `get_Zero`.
> 
> I'd like to look into this before merging, if that's OK.

That compiler error you were getting is because of the [`scaleLinear`](https://github.com/hedgehogqa/fsharp-hedgehog/blob/4e4f5c907cd67b796e66b279b89542b7502cd4df/src/Hedgehog/Range.fs#L180) function used internally by [`linearFrom`](https://github.com/hedgehogqa/fsharp-hedgehog/blob/4e4f5c907cd67b796e66b279b89542b7502cd4df/src/Hedgehog/Range.fs#L215). If you instead work on [`Ticks`](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.ticks?view=net-5.0) and then map to DateTime, it should compile just fine:

```diff
@@ -53,11 +53,18 @@ let ``dateTime randomly generates value between max and min ticks`` () =
 [<Fact>]
 let ``dateTime shrinks to correct mid-value`` () =
     let result =
         property {
             let! actual = 
-              Range.constantFrom (System.DateTime (2000, 1, 1)) System.DateTime.MinValue System.DateTime.MaxValue
+              Range.linearFrom
+                (System.DateTime (2000, 1, 1))
+                     .Ticks
+                 System.DateTime.MinValue
+                     .Ticks
+                 System.DateTime.MaxValue
+                     .Ticks
+              |> Range.map System.DateTime
               |> Gen.dateTime
             System.DateTime.Now =! actual
         }
         |> Property.report
         |> Report.render
```

File: src/Hedgehog/Gen.fs [hunk 2]
```diff
@@ -515,21 +515,32 @@ module Gen =
         return System.Guid bs
     }
 
-    /// Generates a random instant in time expressed as a date and time of day.
+    /// Generates a random DateTime using the specified range.
```
Comment (moodmosaic) [inline src/Hedgehog/Gen.fs:518]:
```suggestion
    /// Generates a random DateTime using the specified range.
    /// For example:
    ///   let range =
    ///      Range.constantFrom
    ///          (System.DateTime (2000, 1, 1)) System.DateTime.MinValue System.DateTime.MaxValue
    ///  Gen.dateTime range
```

**Review by moodmosaic — APPROVED** [review]
Thank you! Looking good :+1: I've suggested a small change in the docs. We can merge after that.

**Comment by cmeeren** [comment]
> If you instead work on [`Ticks`](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.ticks?view=net-5.0) and then map to DateTime, it should compile just fine:

Yes, but then you sidestep the whole generator and have effectively written your own generator. Furthermore, the same applies to `DateTimeOffset`, and that generator is significantly more complicated than just mapping from ticks to `DateTimeOffset`. Is there nothing that can be done to make these generators support non-constant ranges?

**Comment by moodmosaic** [comment]
>Is there nothing that can be done to make these generators support non-constant ranges?

Not without tweaking [`scaleLinear`](https://github.com/hedgehogqa/fsharp-hedgehog/blob/4e4f5c907cd67b796e66b279b89542b7502cd4df/src/Hedgehog/Range.fs#L180) first.

>but then you sidestep the whole generator and have effectively written your own generator

I'm not sure I fully understand. I've added `.Ticks` to each one of the parameters here (and mapped to DateTime)

```
Range.constantFrom (System.DateTime (2000, 1, 1)) System.DateTime.MinValue System.DateTime.MaxValue
```

**Comment by cmeeren** [comment]
> I'm not sure I fully understand. I've added `.Ticks` to each one of the parameters here (and mapped to DateTime)

My bad, I see you map the `Range` and not the `Gen` as I thought.
